"""make_milestone_invoice_id_nullable_and_rename_due_date

Revision ID: 8b67335636bf
Revises: ed344e3e2535
Create Date: 2026-06-10 16:31:39.534546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b67335636bf'
down_revision: Union[str, Sequence[str], None] = 'ed344e3e2535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('end_date', sa.Date(), nullable=True))
    op.alter_column('milestones', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('milestones', 'due_date')
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reminders', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('milestones', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('milestones', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('milestones', 'end_date')
    # ### end Alembic commands ###
