"""add_po_fk_to_invoices_and_reminder_types

Revision ID: ed344e3e2535
Revises: 
Create Date: 2026-06-10 16:29:39.492097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed344e3e2535'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_po_id'), table_name='audit_logs')
    op.drop_constraint(op.f('audit_logs_po_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'po_id')
    op.create_index(op.f('ix_invoices_po_id'), 'invoices', ['po_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'purchase_orders', ['po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_po_id'), table_name='invoices')
    op.add_column('audit_logs', sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_po_id_fkey'), 'audit_logs', 'purchase_orders', ['po_id'], ['id'])
    op.create_index(op.f('ix_audit_logs_po_id'), 'audit_logs', ['po_id'], unique=False)
    # ### end Alembic commands ###
