"""make customer_id nullable on invoices

Revision ID: 51c9ee5b2953
Revises: bf18a8486941
Create Date: 2026-06-08 17:53:55.043960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c9ee5b2953'
down_revision: Union[str, None] = 'bf18a8486941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'sync_status',
               existing_type=postgresql.ENUM('pending', 'synced', 'failed', name='syncstatus'),
               nullable=False)
    op.add_column('invoice_reminders', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoice_reminders', sa.Column('message', sa.Text(), nullable=True))
    op.alter_column('invoices', 'customer_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_reminders', 'message')
    op.drop_column('invoice_reminders', 'sent_at')
    op.alter_column('documents', 'sync_status',
               existing_type=postgresql.ENUM('pending', 'synced', 'failed', name='syncstatus'),
               nullable=True)
    op.alter_column('invoices', 'customer_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
