"""add linked_po_id and customer_name to documents

Revision ID: ad2761f41284
Revises: d7f8abd5ad9f
Create Date: 2026-06-11 03:33:57.848104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2761f41284'
down_revision: Union[str, None] = 'd7f8abd5ad9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('linked_po_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_linked_po_id'), 'documents', ['linked_po_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'purchase_orders', ['linked_po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_linked_po_id'), table_name='documents')
    op.drop_column('documents', 'customer_name')
    op.drop_column('documents', 'linked_po_id')
    # ### end Alembic commands ###
