"""fix_invoice_reminders_and_invoice_date

Revision ID: bf18a8486941
Revises: 85675e866311
Create Date: 2026-06-07 13:56:50.474846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf18a8486941'
down_revision: Union[str, None] = '85675e866311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.add_column('documents', sa.Column('onedrive_url', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('linked_invoice_id', sa.Integer(), nullable=True))
    syncstatus = sa.Enum('pending', 'synced', 'failed', name='syncstatus')
    syncstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('documents', sa.Column('sync_status', sa.Enum('pending', 'synced', 'failed', name='syncstatus'), nullable=True))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_linked_invoice_id'), 'documents', ['linked_invoice_id'], unique=False)
    op.drop_constraint(op.f('documents_invoice_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'invoices', ['linked_invoice_id'], ['id'])
    op.drop_column('documents', 'onedrive_item_id')
    op.drop_column('documents', 'invoice_id')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'size_bytes')
    op.add_column('invoice_reminders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('invoice_reminders', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_invoice_reminders_invoice_id'), 'invoice_reminders', ['invoice_id'], unique=False)
    op.drop_column('invoice_reminders', 'title')
    op.drop_column('invoice_reminders', 'sent')
    op.drop_column('invoice_reminders', 'reminder_date')
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('uq_invoices_company_invoice_number'), table_name='invoices')
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.alter_column('milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('milestones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('milestones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.create_index(op.f('uq_invoices_company_invoice_number'), 'invoices', ['company_id', 'invoice_number'], unique=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('invoice_reminders', sa.Column('reminder_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('invoice_reminders', sa.Column('sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('invoice_reminders', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invoice_reminders_invoice_id'), table_name='invoice_reminders')
    op.alter_column('invoice_reminders', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('invoice_reminders', 'created_at')
    op.add_column('documents', sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('onedrive_item_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_invoice_id_fkey'), 'documents', 'invoices', ['invoice_id'], ['id'])
    op.drop_index(op.f('ix_documents_linked_invoice_id'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('documents', 'sync_status')
    op.drop_column('documents', 'linked_invoice_id')
    op.drop_column('documents', 'onedrive_url')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
