"""add_po_id_reminder_type_to_reminders

Revision ID: d7f8abd5ad9f
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 02:08:47.561174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f8abd5ad9f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_po_id'), table_name='audit_logs')
    op.drop_constraint(op.f('audit_logs_po_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'po_id')
    op.add_column('milestones', sa.Column('end_date', sa.Date(), nullable=True))
    op.alter_column('milestones', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('milestones', 'due_date')
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('reminders', sa.Column('po_id', sa.Integer(), nullable=True))
    op.add_column('reminders', sa.Column('reminder_type', sa.String(length=50), nullable=True))
    op.alter_column('reminders', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reminders_po_id'), 'reminders', ['po_id'], unique=False)
    op.create_foreign_key(None, 'reminders', 'purchase_orders', ['po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_index(op.f('ix_reminders_po_id'), table_name='reminders')
    op.alter_column('reminders', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reminders', 'reminder_type')
    op.drop_column('reminders', 'po_id')
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('milestones', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('milestones', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('milestones', 'end_date')
    op.add_column('audit_logs', sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_po_id_fkey'), 'audit_logs', 'purchase_orders', ['po_id'], ['id'])
    op.create_index(op.f('ix_audit_logs_po_id'), 'audit_logs', ['po_id'], unique=False)
    # ### end Alembic commands ###
