"""add_purchase_orders_and_po_fields

Revision ID: ea04b7e53bb0
Revises: 185d7b13b1b0
Create Date: 2026-06-10 04:34:10.132795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea04b7e53bb0'
down_revision: Union[str, None] = '185d7b13b1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('billing_terms', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('authorised_signatory', sa.String(length=255), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'invoiced', 'partially_invoiced', 'closed', name='postatus'), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.add_column('audit_logs', sa.Column('po_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_po_id'), 'audit_logs', ['po_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'purchase_orders', ['po_id'], ['id'])
    documenttype = sa.Enum('invoice', 'po', 'receipt', name='documenttype')
    documenttype.create(op.get_bind(), checkfirst=True)
    milestonesource = sa.Enum('manual', 'po_generated', name='milestonesource')
    milestonesource.create(op.get_bind(), checkfirst=True)
    op.add_column('documents', sa.Column('document_type', sa.Enum('invoice', 'po', 'receipt', name='documenttype'), nullable=False))
    op.add_column('milestones', sa.Column('po_id', sa.Integer(), nullable=True))
    op.add_column('milestones', sa.Column('source', sa.Enum('manual', 'po_generated', name='milestonesource'), nullable=True))
    op.execute("UPDATE milestones SET source = 'manual' WHERE source IS NULL")
    op.alter_column('milestones', 'source', nullable=False)
    op.create_index(op.f('ix_milestones_po_id'), 'milestones', ['po_id'], unique=False)
    op.create_foreign_key(None, 'milestones', 'purchase_orders', ['po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_index(op.f('ix_milestones_po_id'), table_name='milestones')
    op.drop_column('milestones', 'source')
    op.drop_column('milestones', 'po_id')
    op.drop_column('documents', 'document_type')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_po_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'po_id')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
